# Generated by Django 4.0.4 on 2022-05-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactormodel',
            name='gender',
            field=models.CharField(choices=[('woman', '女'), ('man', '男')], default='man', max_length=50, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='charactormodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
    ]
