# Generated by Django 4.0.4 on 2022-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_charactormodel_gender_alter_charactormodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactormodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='charactormodel',
            name='name',
            field=models.TextField(null=True, verbose_name='特徴'),
        ),
    ]
