# Generated by Django 4.0.4 on 2022-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_remove_charactormodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactormodel',
            name='feature',
            field=models.TextField(default='', verbose_name='特徴'),
        ),
        migrations.AlterField(
            model_name='charactormodel',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='名前'),
        ),
    ]
