# Generated by Django 4.0.4 on 2022-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_charactormodel_feature_alter_charactormodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactormodel',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], default='man', max_length=50, verbose_name='性別'),
        ),
    ]
