# Generated by Django 4.0.4 on 2022-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_alter_charactormodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactormodel',
            name='image_link',
            field=models.TextField(default='', verbose_name='画像リンク'),
        ),
        migrations.AddField(
            model_name='charactormodel',
            name='page_link',
            field=models.TextField(default='', verbose_name='ページリンク'),
        ),
    ]
